---
title: Justinsjlee.Github.Io
timezone: America/Toronto
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
name: Justin SJ Lee
author:

  name: Justin SJ Lee
  medium: justinsjlee
  github: justinsjlee
  twitter: justinsjlee
  linkedin: justinsjlee
  email: hi@justinsjlee.com
google-analytics:
  id: UA-75000604-7
disqus:
  id:
url: http://www.justinsjlee.com
baseurl: ''
permalink: "/:year-:month-:day/:title/"
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
kramdown:
  imput: GFM
nav:
- name: About
  url: "/about"
- name: Blog
  url: "/blog"
- name: Tags
  url: "/tags"
- name: Projects
  url: "/projects"

sass:
  sass_dir: _sass
  style: :compressed
gems:
- jekyll-seo-tag
- jekyll-paginate
exclude:
- vendor
